### ISSUE TITLE
平滑滚动插件在vuepress2中如何使用？

### ISSUE THREAD

**Issue by Rain-Hsiang** [meathill/gitbook-design-patterns-in-jquery#5]
平滑滚动插件在vuepress2中如何使用？
vuepress-plugin-smooth-scroll这个插件是1.x的，2.x中无法使用，官方git里面提问用的是新建index.scss但测试无效
[https://github.com/vuepress/vuepress-next/issues/590](https://github.com/vuepress/vuepress-next/issues/590)
```css
:root {
  scroll-behavior: smooth;
}
```
